services:
  backend:
    build: ./backend
    command: daphne -b 0.0.0.0 -p 8000 crawler.asgi:application
    environment:
      - DJANGO_SETTINGS_MODULE=crawler.settings
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    # stdin_open: true
    # tty: true

  redis:
    image: redis:8.0-rc1-alpine
    ports:
      - 6379:6379
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgres/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=webcrawler
      - POSTGRES_PASSWORD=webcrawler
      - POSTGRES_DB=webcrawler_db

volumes:
  postgres_data:
